# Generated by Django 5.2.4 on 2025-07-17 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('poem', 'Poem')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chunking_strategy', models.CharField(choices=[('line', 'Line'), ('sentence', 'Sentence'), ('speaker_turn', 'Speaker turn'), ('custom', 'Custom')], default='line', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('speaker', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='memorise.section')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='memorise.work')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_ids', models.JSONField(default=list)),
                ('mode', models.CharField(choices=[('repetition', 'Repetition'), ('practice', 'Practice'), ('test', 'Test')], max_length=50)),
                ('score', models.FloatField(default=0.0)),
                ('cap', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='memorise.work')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='memorise.work'),
        ),
        migrations.CreateModel(
            name='UserUnitProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('last_practiced_at', models.DateTimeField(auto_now=True)),
                ('times_practiced', models.PositiveIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='memorise.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='UserWorkProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('last_practiced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_progress', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='memorise.work')),
            ],
            options={
                'unique_together': {('user', 'work')},
            },
        ),
    ]
