# Generated by Django 5.2.4 on 2025-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorise', '0002_tag_work_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Paste full poem text here'),
        ),
    ]
