# Generated by Django 5.2.4 on 2025-07-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorise', '0003_work_raw_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['section__order_index', 'order_index']},
        ),
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
