# Generated by Django 5.2.4 on 2025-07-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorise', '0004_alter_section_options_alter_unit_options_work_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
